[versions]
accompanist = "0.26.2-beta"
activityCompose = "1.6.0-rc01"
androidxTest = "1.5.0-alpha02"
androidxTestExtJUnit = "1.1.4-alpha07"
androidxTestOrchestrator = "1.4.2-alpha04"
androidxTestRules = "1.4.1-alpha07"
androidxTestServices = "1.4.1"
appCompat = "1.5.0"
assertk = "0.25"
coil = "2.2.0"
compose = "1.3.0-beta01"
composeCompiler = "1.3.0-beta01"
composeMaterial3 = "1.0.0-beta01"
composeUiTestJUnit4 = "1.2.1"
daggerHilt = "2.43.2"
datastore = "1.0.0"
desugar = "1.2.2"
espresso-core = "3.5.0-alpha07"
firebaseBom = "30.3.2"
glance = "1.0.0-alpha04"
gradlePlugins-agp = "7.4.0-beta01"
gradlePlugins-crashlytics = "2.9.1"
gradlePlugins-detekt = "1.21.0"
gradlePlugins-gms = "4.3.13"
gradlePlugins-hilt = "2.43.2"
gradlePlugins-junit5 = "1.8.2.1"
gradlePlugins-kotlinter = "3.11.1"
gradlePlugins-ksp = "1.7.10-1.0.6"
gradlePlugins-protobuf = "0.8.19"
gradlePlugins-shot = "5.14.1"
gradlePlugins-versionCatalog = "0.6.1"
gradlePlugins-versionsBenManes = "0.42.0"
hilt = "1.0.0"
hiltNavigationCompose = "1.0.0"
junit = "5.9.0"
kotlin = "1.7.10"
kotlinxCoroutinesTest = "1.6.4"
lifecycle = "2.6.0-alpha01"
navigationCompose = "2.5.1"
protobuf = "3.21.5"
room = "2.5.0-alpha03"
splashscreen = "1.0.0-rc01"
timber = "5.0.1"
uiAutomator = "2.2.0"

[libraries]
androidx-activity-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
androidx-compose-material3WindowSizeClass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "composeMaterial3" }
androidx-compose-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-runtimeLivedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-uiTest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUiTestJUnit4" }
androidx-compose-ui-uiTest-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-compose-ui-uiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-uiTooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-glance = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-hilt-hiltCommon = { module = "androidx.hilt:hilt-common", version.ref = "hilt" }
androidx-hilt-hiltCompiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt" }
androidx-hilt-hiltNavigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-room-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJUnit" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidxTestOrchestrator" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
androidx-test-services = { module = "androidx.test.services:test-services", version.ref = "androidxTestServices" }
androidx-test-uiAutomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiAutomator" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
coilKt-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
com-android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
google-accompanistFlowLayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
google-accompanistNavAnimations = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
google-accompanistNavMaterial = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
google-accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
google-accompanistSystemUIController = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
google-dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "daggerHilt" }
google-dagger-daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerHilt" }
google-dagger-hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "daggerHilt" }
google-dagger-hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "daggerHilt" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
jakes-timber-timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }

[bundles]
accompanist = [
    "google-accompanistFlowLayout",
    "google-accompanistNavAnimations",
    "google-accompanistNavMaterial",
    "google-accompanistPermissions",
    "google-accompanistSystemUIController",
]
androidxTestUtils = [
    "androidx-test-orchestrator",
    "androidx-test-services",
]
compose = [
    "androidx-compose-foundation",
    "androidx-compose-material",
    "androidx-compose-material3",
    "androidx-compose-material3WindowSizeClass",
    "androidx-compose-materialIconsExtended",
    "androidx-compose-runtimeLivedata",
    "androidx-compose-ui",
]
composeTest = [
    "androidx-compose-ui-uiTest-junit4",
    "androidx-compose-ui-uiTest-manifest",
    "androidx-test-core",
    "androidx-test-espresso-core",
    "androidx-test-ext-junit",
    "androidx-test-rules",
]
composeUiTooling = [
    "androidx-compose-ui-uiTooling",
    "androidx-compose-ui-uiTooling-preview",
]
datastore = [
    "androidx-datastore",
    "google-protobuf-javalite",
]
firebase = [
    "google-firebase-analytics-ktx",
    "google-firebase-crashlytics-ktx",
]
hilt = [
    "androidx-hilt-hiltCommon",
    "google-dagger-dagger",
    "google-dagger-hiltAndroid",
]
hiltKapt = [
    "androidx-hilt-hiltCompiler",
    "google-dagger-daggerCompiler",
    "google-dagger-hiltCompiler",
]
lifecycle = [
    "androidx-lifecycle-lifecycleRuntimeKtx",
    "androidx-lifecycle-lifecycleViewmodelCompose",
]
room = [
    "androidx-room-roomKtx",
    "androidx-room-roomRuntime",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "gradlePlugins-junit5" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "gradlePlugins-crashlytics" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "gradlePlugins-detekt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "gradlePlugins-gms" }
hilt = { id = "dagger.hilt.android.plugin", version.ref = "gradlePlugins-hilt" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "gradlePlugins-kotlinter" }
ksp = { id = "com.google.devtools.ksp", version.ref = "gradlePlugins-ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "gradlePlugins-protobuf" }
shot = { id = "shot", version.ref = "gradlePlugins-shot" }
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "gradlePlugins-versionCatalog" }
versionsBenManes = { id = "com.github.ben-manes.versions", version.ref = "gradlePlugins-versionsBenManes" }
